src/Entity/Producto.php
<?php

namespace App\Entity;

use App\Repository\ProductoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=ProductoRepository::class)
 * @Vich\Uploadable
 */
class Producto
{
	/**
	 * @ORM\Id
	 * @ORM\GeneratedValue
	 * @ORM\Column(type="integer")
	 */
	private $id;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\FacturasProducto", mappedBy="id_producto")
	 */
	private $facturas;

	/**
	 * @ORM\Column(type="string", length=255)
	 */
	private $marca;

	/**
	 * @ORM\Column(type="string", length=255)
	 */
	private $modelo;

	/**
	 * @ORM\Column(type="string", length=255)
	 */
	private $serie;

	/**
	 * @ORM\Column(type="float")
	 */
	private $precioC;

	/**
	 * @ORM\Column(type="float")
	 */
	private $precioV;

	/**
	 * @ORM\Column(type="float")
	 */
	private $ganancia;

	/**
	 * @ORM\Column(type="float")
	 */
	private $xcientoganancia;

	/**
	 * @ORM\Column(type="integer")
	 */
	private $cantidad_taller;

	/**
	 * @ORM\Column(type="integer")
	 */
	private $cantidad_inventario;
	/**
	 * @ORM\Column(type="boolean")
	 */
	private $active;

	/**
	 * NOTE: This is not a mapped field of entity metadata, just a simple property.
	 *
	 * @Vich\UploadableField(mapping="product_image", fileNameProperty="imageName", size="imageSize")
	 *
	 * @var File|null
	 */
	private $imageFile;

	/**
	 * @ORM\Column(type="string", nullable=true)
	 *
	 * @var string|null
	 */
	private $imageName;

	/**
	 * @ORM\Column(type="integer", nullable=true)
	 *
	 * @var int|null
	 */
	private $imageSize;

	/**
	 * @ORM\Column(type="datetime", nullable=true)
	 *
	 * @var \DateTimeInterface|null
	 */
	private $updatedAt;

	/**
	 * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
	 */
	public function setImageFile(?File $imageFile = null): void
	{
		$this->imageFile = $imageFile;

		if (null !== $imageFile) {
			// It is required that at least one field changes if you are using doctrine
			// otherwise the event listeners won't be called and the file is lost
			$this->updatedAt = new \DateTimeImmutable();
		}
	}

	public function getImageFile(): ?File
	{
		return $this->imageFile;
	}

	public function getImageName(): ?string
	{
		return $this->imageName;
	}

	public function setImageName(?string $imageName): self
	{
		$this->imageName = $imageName;

		return $this;
	}

	public function getImageSize(): ?int
	{
		return $this->imageSize;
	}

	public function setImageSize(?int $imageSize): self
	{
		$this->imageSize = $imageSize;

		return $this;
	}

	public function getUpdatedAt(): ?\DateTimeInterface
	{
		return $this->updatedAt;
	}

	public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
	{
		$this->updatedAt = $updatedAt;

		return $this;
	}

	public function __construct()
	{
		$this->facturas = new ArrayCollection();
	}

	public function getCantidadTaller(): ?int
	{
		return $this->cantidad_taller;
	}

	public function setCantidadTaller(int $cantidad_taller): self
	{
		$this->cantidad_taller = $cantidad_taller;

		return $this;
	}

	public function getCantidadInventario(): ?int
	{
		return $this->cantidad_inventario;
	}

	public function setCantidadInventario(int $cantidad_inventario): self
	{
		$this->cantidad_inventario = $cantidad_inventario;

		return $this;
	}

	public function getActive(): ?bool
	{
		return $this->active;
	}

	public function setActive(bool $active): self
	{
		$this->active = $active;

		return $this;
	}

	public function getId(): ?int
	{
		return $this->id;
	}

	public function getMarca(): ?string
	{
		return $this->marca;
	}

	public function setMarca(string $marca): self
	{
		$this->marca = $marca;

		return $this;
	}

	public function getModelo(): ?string
	{
		return $this->modelo;
	}

	public function setModelo(string $modelo): self
	{
		$this->modelo = $modelo;

		return $this;
	}

	public function getSerie(): ?string
	{
		return $this->serie;
	}

	public function setSerie(string $serie): self
	{
		$this->serie = $serie;

		return $this;
	}

	public function getPrecioC(): ?float
	{
		return $this->precioC;
	}

	public function setPrecioC(float $precioC): self
	{
		$this->precioC = $precioC;

		return $this;
	}

	public function getPrecioV(): ?float
	{
		return $this->precioV;
	}

	public function setPrecioV(float $precioV): self
	{
		$this->precioV = $precioV;

		return $this;
	}

	public function getGanancia(): ?float
	{
		return $this->ganancia;
	}

	public function setGanancia(float $ganancia): self
	{
		$this->ganancia = $ganancia;

		return $this;
	}

	public function __toString()
	{
		return $this->marca;
	}

	/**
	 * @return Collection|FacturasProducto[]
	 */
	public function getFacturas(): Collection
	{
		return $this->facturas;
	}

	public function addFactura(FacturasProducto $factura): self
	{
		if (!$this->facturas->contains($factura)) {
			$this->facturas[] = $factura;
			$factura->setIdProducto($this);
		}

		return $this;
	}

	public function removeFactura(FacturasProducto $factura): self
	{
		if ($this->facturas->removeElement($factura)) {
			// set the owning side to null (unless already changed)
			if ($factura->getIdProducto() === $this) {
				$factura->setIdProducto(null);
			}
		}

		return $this;
	}

	public function getXcientoganancia(): ?float
	{
		return $this->xcientoganancia;
	}

	public function setXcientoganancia(float $xcientoganancia): self
	{
		$this->xcientoganancia = $xcientoganancia;

		return $this;
	}
}

src/Controller/TallerController.php
<?php

namespace App\Controller;

use App\Entity\Cliente;
use App\Entity\Facturas;
use App\Entity\FacturasProducto;
use App\Entity\FacturasServicio;
use App\Entity\Logs;
use App\Entity\Producto;
use App\Entity\Servicio;
use App\Entity\System;
use App\Entity\User;
use App\Form\AddInventarioType;
use App\Form\FacturaType;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Mpdf\Mpdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/taller")
 */
class TallerController extends AbstractController
{
	private $logsOb;

	public function __construct()
	{
		$this->logsOb = new LogsController();
	}

	/**
	 * @Route("", name="app_taller")
	 */
	public function index(): Response
	{
		$items_data = $this->getDoctrine()->getRepository(Producto::class);
		$data = $items_data->showAllTaller();

		return $this->render('taller/index.html.twig',
			[
				'data' => $data
			]
		);
	}

	/**
	 * @Route("/factura", name="app_factura")
	 */
	public function facturaAction(Request $request): Response
	{
		$factura = new Facturas();
		$form = $this->createForm(FacturaType::class, $factura);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {

			$user = $this->getDoctrine()->getRepository(User::class)->find($this->getUser());
			$usercant2 = $this->getDoctrine()->getRepository(User::class)->countActiveUsers();
			$usercant = count($usercant2);
			$system = $this->getDoctrine()->getRepository(System::class)->find(1);

			$em = $this->getDoctrine()->getManager();
			$createCliente = true;

			if ($factura->getIdCliente() === null) {
				$cliente = new Cliente();
				$clienteForm = $request->get('cliente_name');
				if ($clienteForm !== null) {
					$cliente->setName(ucfirst($clienteForm));
				} else {
					$createCliente = false;
				}
				$tellForm = $request->get('telefono_name');
				if ($tellForm !== null) {
					if (strlen($tellForm) == 8) {
						$cliente->setTell($tellForm);
					} else {
						$createCliente = false;
					}
				} else {
					$createCliente = false;
				}
				$cliente->setActive(1);
				$cliente->setDescuento(0);
				if ($createCliente === true) {
					$factura->setIdCliente($cliente);
					$em->persist($cliente);
				}
			} else {
				$cliente = $this->getDoctrine()->getRepository(Cliente::class)->find($factura->getIdCliente());
			}

			$factura->setIdUser($user);
			$factura->setFecha(new \DateTime("now"));
			$factura->setSaldoRetenidoP(0);
			$factura->setSaldoRetenidoS(0);
			$factura->setSaldoRetenidoI(0);
			$factura->setSaldoRetenidoFI(0);
			$factura->setSaldoRetenidoFG(0);
			$factura->setActive(1);
			$facturaTotalTemporal = 0;
			$facturaTotalRealTeamporal = 0;
			$array_facturas_p = [];
			$array_facturas_s = [];
			$detalles = "";

			$products_array = $request->get('productsArray');
			if ($products_array != null) {
				sort($products_array);
				$products_cant = array_count_values($products_array);
				$products_array = array_unique($products_array);

				foreach ($products_array as $product) {

					$factura_productos = new FacturasProducto();
					$product_data = $this->getDoctrine()->getRepository(Producto::class)->find($product);

					if ($product_data->getCantidadTaller() - $products_cant[$product] >= 0) {
						//tabla facturas producto
						$factura_productos->setIdFactura($factura);
						$factura_productos->setIdProducto($product_data);
						$factura_productos->setPrecio($product_data->getPrecioV());
						$factura_productos->setCantidad($products_cant[$product]);
						$product_data->setCantidadTaller($product_data->getCantidadTaller() - $products_cant[$product]);

						//array y logs
						$array_facturas_p[] = $factura_productos;
						$detalles = $product_data->getMarca() . ","
							. $product_data->getPrecioV() . ","
							. $factura_productos->getCantidad() . "|";

						//tabla facturas
						$ganancia_producto = ($product_data->getPrecioV() - $product_data->getPrecioC()) * $products_cant[$product];
						$ganancia_real_producto = $ganancia_producto - ($ganancia_producto * $cliente->getDescuento() / 100);

						$total_venta_producto = $product_data->getPrecioV() * $products_cant[$product];
						$total_real_venta_producto = $total_venta_producto - ($ganancia_producto * $cliente->getDescuento() / 100);

						$facturaTotalTemporal += $total_venta_producto;
						$facturaTotalRealTeamporal += $total_real_venta_producto;

						//$total_real_venta_producto = $product_data->getPrecioC() - $product_data->getPrecioV() * $cliente->getDescuento() / 100;
						//$ganancia_producto = ($total_real_venta_producto - $product_data->getPrecioC()) * $products_cant[$product];
						$saldo_r_producto_t = $ganancia_real_producto * $product_data->getXcientoganancia() / 100;
						$saldo_r_indirecto_t = $ganancia_real_producto * $system->getWinproduct() / 100 * ($usercant - 1);
						$inversion_recuperada = $ganancia_real_producto - $saldo_r_producto_t - $saldo_r_indirecto_t;

						$factura->setSaldoRetenidoP($factura->getSaldoRetenidoP() + $saldo_r_producto_t);
						$factura->setSaldoRetenidoI($factura->getSaldoRetenidoI() + $saldo_r_indirecto_t);
						$factura->setSaldoRetenidoFI($factura->getSaldoRetenidoFI() + ($product_data->getPrecioC() * $products_cant[$product]));
						$factura->setSaldoRetenidoFG($factura->getSaldoRetenidoFG() + $inversion_recuperada);
					}
				}
				foreach ($array_facturas_p as $prod) {
					$em->persist($prod);
					$factura->addProducto($prod);
				}
			}

			$service_array = $request->get('servicesArray');
			if ($service_array != null) {
				sort($service_array);
				$service_cant = array_count_values($service_array);
				$service_array = array_unique($service_array);

				foreach ($service_array as $service) {
					//tabla factura servicio
					$factura_servicios = new FacturasServicio();
					$service_data = $this->getDoctrine()->getRepository(Servicio::class)->find($service);
					$factura_servicios->setIdFactura($factura);
					$factura_servicios->setIdServicio($service_data);
					$factura_servicios->setPrecio($service_data->getPrecio());
					$factura_servicios->setCantidad($service_cant[$service]);

					//array y logs
					$array_facturas_s[] = $factura_servicios;
					$detalles = $service_data->getName() . ","
						. $service_data->getPrecio() . ","
						. $factura_servicios->getCantidad() . "|";

					//tabla facturas
					$total_venta_servicio = $service_data->getPrecio() * $service_cant[$service];
					$total_real_venta_servicio = $total_venta_servicio - $total_venta_servicio * $cliente->getDescuento() / 100;

					$facturaTotalTemporal += $total_venta_servicio;
					$facturaTotalRealTeamporal += $total_real_venta_servicio;

					//$total_real_venta_servicio = $service_data->getPrecio() - $service_data->getPrecio() * $cliente->getDescuento() / 100;
					$saldo_r_servicio_t = $total_real_venta_servicio * $service_data->getXcientoganancia() / 100;
					$saldo_r_indirecto_t = $total_real_venta_servicio * $system->getWinservice() / 100 * ($usercant - 1);
					$inversion_recuperada = $total_real_venta_servicio - $saldo_r_servicio_t - $saldo_r_indirecto_t;

					$factura->setSaldoRetenidoS($factura->getSaldoRetenidoS() + $saldo_r_servicio_t);
					$factura->setSaldoRetenidoI($factura->getSaldoRetenidoI() + $saldo_r_indirecto_t);
					//$factura->setSaldoRetenidoFI($factura->getSaldoRetenidoFI() + $service_data->getPrecio() - $saldo_r_servicio_t - $saldo_r_indirecto_t);
					$factura->setSaldoRetenidoFG($factura->getSaldoRetenidoFG() + $inversion_recuperada);
				}
				foreach ($array_facturas_s as $serv) {
					$em->persist($serv);
					$factura->addServicio($serv);
				}
			}

			if ($service_array == null && $products_array == null) {
				return $this->redirectToRoute('app_factura');
			}

			$factura->setTotal($facturaTotalTemporal);
			$factura->setTotalReal($facturaTotalRealTeamporal);
			$factura->setXpagar($factura->getTotalReal());
			$factura->setDescuento($cliente->getDescuento());

			$em->persist($factura);

			$log = $this->logsOb->generateLogs($cliente, $factura, $this->getUser(), "factura", $detalles);
			$em->persist($log);

			if ($facturaTotalTemporal > 0 && $createCliente === true) {
				try {
					$em->flush();
				} catch (UniqueConstraintViolationException $e) {
					return $this->redirectToRoute('app_factura');
				}
				return $this->redirectToRoute('app_factura_detalles', [
					"id" => $factura->getId()
				]);
			}

			return $this->redirectToRoute('app_user_factura');
		}

		$items_data = $this->getDoctrine()->getRepository(Producto::class);
		$data = $items_data->showAllTaller();

		$service_data = $this->getDoctrine()->getRepository(Servicio::class);
		$datas = $service_data->findAllServices();

		return $this->render('taller/factura.html.twig',
			[
				'form' => $form->createView(),
				'data' => $data,
				'service' => $datas
			]
		);
	}

	/**
	 * @Route("/eliminar_factura/{id}", name="app_eliminar_factura", requirements={"id"="\d+"} ,methods={"POST"})
	 */
	public function eliminar($id = null)
	{
		if ($id != null) {
			$factura = $this->getDoctrine()->getRepository(Facturas::class)->find($id);
			if ($factura) {
				$productos = $this->getDoctrine()->getRepository(FacturasProducto::class)->findBy([
					'id_factura' => $id
				]);
				$servicios = $this->getDoctrine()->getRepository(FacturasServicio::class)->findBy([
					'id_factura' => $id
				]);

				if ($factura->getTotalReal() == $factura->getXpagar()) {
					if ($this->getUser() == $factura->getIdUser() || $this->getUser()->getRoles()[0] == "ROLE_ADMIN") {
						$em = $this->getDoctrine()->getManager();
						foreach ($productos as $producto) {
							$producto->getIdProducto()->setCantidadTaller($producto->getIdProducto()->getCantidadTaller() + $producto->getCantidad());

templates/taller/add_inventario.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Trasladar a Inventario
{% endblock %}

{% block page_name %}
    Trasladar a Inventario
{% endblock %}

{% block main_content %}
    <div class="card card-primary container-fluid">
        {{ form_start(form, { attr: {class: 'submit-p-form'} }) }}
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <label class="">Cantidad en Taller</label><label class="form-control">{{ cantidad_actual }} </label>
                </div>
                <div class="col-md-3">
                    {{ form_row(form.cantidadInventario, { attr: {'autocomplete': 'off'} } ) }}
                </div>
                <div class="col-md-3">
                    {{ form_row(form.add, {attr:{text: 'Actualizar', class: 'btn-primary btn-block submit-p-btn', style: 'margin-top: 32px!important'}}) }}
                </div>
                <div class="col-md-3">
                    <a href="{{ path('app_taller') }}"><input class="btn btn-danger btn-block" type="button"
                                                             value="Cancelar" style="margin-top: 32px!important"></a>
                </div>
            </div>
        </div>
        {{ form_end(form) }}
        <!-- /.card-body -->
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('plugins/toastr/toastr.min.js') }}"></script>
    <script src="{{ asset('dist/js/alerts.js') }}"></script>
    {% for msg in app.flashes('error') %}
        <script>
            showAlert('error', '{{ msg }}', 'Error');
        </script>
    {% endfor %}
{% endblock %}

templates/taller/detalles.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Detalles de Factura
{% endblock %}

{% block page_name %}
    Detalles de Factura
{% endblock %}

{% block page_btns %}
    <a type="button" class="btn btn-primary m-1 float-right col-md-3" href="{{ path('app_factura') }}">
        Nueva Factura
    </a>
    <a type="button" class="btn btn-primary m-1 float-right col-md-3" href="{{ path('app_user_factura_xcobrar') }}">
        Por Cobrar
    </a>
    <a type="button" class="btn btn-primary m-1 float-right col-md-3" href="{{ path('app_user_factura') }}">
        Mis Facturas
    </a>
{% endblock %}

{% block main_content %}
    {% for factura in facturas %}
        <div class="invoice p-3 mb-3 container-fluid">
            <div class="row">
                <div class="col-12">
                    <h4>
                        <small class="float-right">Fecha de Factura: {{ factura.fecha|date("d/m/Y") }}</small>
                    </h4>
                </div>
            </div>
            <div class="row invoice-info mt-3">
                <div class="col-sm-2 invoice-col pl-4">
                    <h5 class="d-inline-block">Usuario:</h5> {{ factura.iduser }}
                </div>
                <div class="col-sm-2 invoice-col pb-4 pl-4">
                    <h5 class="d-inline-block">Cliente:</h5> {{ factura.idcliente }}
                </div>
                <div class="col-sm-8 invoice-col pb-4 pl-4">
                    <a href="{{ path('app_factura_detalles_pdf', {'id': factura.id }) }}" target="_blank"
                       class="btn btn-default float-right"><i
                                class="fas fa-print"></i>
                        Imprimir</a>
                </div>
            </div>
            <div class="row">
                <div class="col-12 table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th width="28%">Nombre</th>
                            <th width="18%">Tipo</th>
                            <th width="18%">Cantidad</th>
                            <th width="18%">Precio</th>
                            <th width="18%">Subtotal</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for producto in factura.productos %}
                            <tr>
                                <td>
                                    {{ producto.idproducto.serie }}
                                    {{ producto.idproducto.marca }}
                                    {{ producto.idproducto.modelo }}
                                </td>
                                <td>Producto</td>
                                <td>{{ producto.cantidad }}</td>
                                <td>{{ producto.precio }}</td>
                                <td>{{ producto.cantidad * producto.precio }}</td>
                            </tr>
                        {% endfor %}
                        {% for servicio in factura.servicios %}
                            <tr>
                                <td>{{ servicio.idservicio.name }}</td>
                                <td>Servicio</td>
                                <td>{{ servicio.cantidad }}</td>
                                <td>{{ servicio.precio }}</td>
                                <td>{{ servicio.cantidad * servicio.precio }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
            <hr>
            <div class="row">
                <!-- /.col -->
                <div class="col-sm-6">
                    <p class="pl-3">Fecha del Pago: {{ "now"|date("d/m/Y") }}</p>

                    <div class="table-responsive col-11">
                        <table class="table">
                            <tbody>
                            <tr>
                                <th style="width:50%">Subtotal:</th>
                                <td>{{ factura.total }}</td>
                            </tr>
                            <tr>
                                <th>Descuento ({{ factura.descuento }}%)</th>
                                <td>{{ factura.total-factura.totalreal }}</td>
                            </tr>
                            <tr>
                                <th>Total:</th>
                                <td>{{ factura.totalreal }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="col-sm-6">
                    {% if factura.xpagar != 0 %}
                        {{ form_start(form, {attr:{'class':'row submit-p-form'}}) }}
                    {% endif %}
                    <div class="col-12">
                        <div class="row p-2 border-left-0 border-top-0 border-right-0 border-bottom mb-3">
                            <div class="col-6">Deuda:</div>
                            <div class="col-6 pl-0">{{ factura.xpagar }}</div>
                        </div>
                    </div>
                    {% if factura.xpagar != 0 %}
                        <div class="col-md-6">
                            <p>Metodo de Pago:</p>
                            <select name="tipopago" id="tipopago" class="form-control" required>
                                <option value="1">Efectivo</option>
                                <option value="2">Transfermovil</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <p>Cantidad a pagar:</p>
                            <input class="form-control" type="text" name="pagar" required autocomplete="off">
                        </div>
                    {% endif %}
                    <div class="col-12 no-print mt-4">
                        {% if factura.totalreal == factura.xpagar %}
                            <button type="button" onclick="delFactura({{ factura.id }})" class="btn btn-danger float-right col-md-3 ml-2 mb-2" title="Cancelar">Cancelar</button>
                        {% endif %}
                        {% if factura.xpagar != 0 %}
                            {{ form_row(form.submit, {attr: {'class':'btn btn-primary float-right col-md-3 submit-p-btn'}}) }}
                            {{ form_row(form.id_cliente, { attr: {'readonly': 'readonly', 'class': 'd-none'}, label:'', label_attr:{'class':'d-none'} } ) }}
                        {% endif %}
                    </div>
                    {% if factura.xpagar != 0 %}
                        {{ form_end(form) }}
                    {% endif %}
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->

            <!-- this row will not appear when printing -->
        </div>
    {% endfor %}
    {% for factura in facturas %}
        <div class="invoice p-3 mb-3 container-fluid">
            <div class="row">
                <div class="col-12">
                    <h4>
                        <small>Historial de Pagos</small>
                    </h4>
                </div>
            </div>
            <div class="row">
                <div class="col-12 table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Fecha</th>
                            <th>Usuario</th>
                            <th>Metodo</th>
                            <th>Cantidad</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for log in logs %}
                            <tr>
                                <td>{{ log.fecha|date("d/m/Y") }}</td>
                                <td>{{ log.iduser }}</td>
                                {% set array = log.detalles|split(',',3) %}
                                <td>{{ array[0] }}</td>
                                <td>{{ array[1] }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('dist/js/actions.js') }}"></script>
{% endblock %}

templates/taller/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheet %}
    <link rel="stylesheet" href="{{ asset('plugins/datatables/datatables.min.css') }}">
{% endblock %}

{% block title %}
    Taller
{% endblock %}

{% block page_name %}
    Taller
{% endblock %}

{% block page_btns %}
    <a type="button" class="btn btn-primary m-1 float-right col-md-3" href="{{ path('app_factura') }}">
        Nueva Factura
    </a>
    <a type="button" class="btn btn-primary m-1 float-right col-md-3" href="{{ path('app_user_factura_xcobrar') }}">
        Por Cobrar
    </a>
    <a type="button" class="btn btn-primary m-1 float-right col-md-3" href="{{ path('app_user_factura') }}">
        Mis Facturas
    </a>
{% endblock %}


{% block main_content %}

    <div class="card card-primary container-fluid">
        <div class="card-body">
            <div class="table-responsive">
                <table id="dataTable" class="table table-striped" width="100%" cellspacing="0">
                    <thead>
                    <tr class="text-center">
                        <th width="14%">Tipo</th>
                        <th width="14%">Marca</th>
                        <th width="14%">Modelo</th>
                        <th width="14%">Precio_Venta</th>
                        <th width="14%">Cantidad</th>
                        {% if is_granted('ROLE_ADMIN') %}
                            <th width="30%">Acciones</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in data %}
                        <tr class="text-center">
                            <td class="text-left pl-4">{{ item.serie }}</td>
                            <td>{{ item.marca }}</td>
                            <td>{{ item.modelo }}</td>
                            <td>{{ item.precioV }}</td>
                            <td>{{ item.cantidad_taller }}</td>
                            {% if is_granted('ROLE_ADMIN') %}
                                <td class="text-center">
                                    <a class="btn btn-sm btn-default mr-1 ml-1 mb-1" title="Trasladar a Inventario"
                                       href="{{ path('app_taller_add_inventario', {'id': item.id}) }}">
                                        <i class="fas fa-arrow-right text-primary"></i>
                                    </a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('dist/js/actions.js') }}"></script>
    <script src="{{ asset('plugins/jquery-easing/jquery.easing.min.js') }}"></script>
    <script src="{{ asset('plugins/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset('plugins/users.js') }}"></script>
    <script src="{{ asset('plugins/toastr/toastr.min.js') }}"></script>
    <script src="{{ asset('dist/js/alerts.js') }}"></script>
    {% for msg in app.flashes('success') %}
        <script>
            showAlert('success', '{{ msg }}', 'Correcto');
        </script>
    {% endfor %}
{% endblock %}